import type { MigrationBuilder } from "node-pg-migrate";

import {
  DATABASE_IDENTITY_AUDIT_APPEND_ONLY_SQL,
  DATABASE_IDENTITY_AUDIT_INDEX_SQL,
  DATABASE_IDENTITY_AUDIT_TABLE_SQL,
  DATABASE_IDENTITY_CHALLENGES_INDEXES_SQL,
  DATABASE_IDENTITY_CHALLENGES_TABLE_SQL,
  DATABASE_IDENTITY_CONTRACT_INSERT_SQL,
  DATABASE_IDENTITY_IDEMPOTENCY_INDEX_SQL,
  DATABASE_IDENTITY_IDEMPOTENCY_TABLE_SQL,
  DATABASE_IDENTITY_OUTBOX_INDEX_SQL,
  DATABASE_IDENTITY_OUTBOX_TABLE_SQL,
  DATABASE_IDENTITY_RATE_LIMITS_INDEX_SQL,
  DATABASE_IDENTITY_RATE_LIMITS_TABLE_SQL,
  DATABASE_IDENTITY_RESTORE_FEATURE_FLAGS_CONTRACT_SQL,
  DATABASE_IDENTITY_SESSIONS_INDEX_SQL,
  DATABASE_IDENTITY_SESSIONS_TABLE_SQL,
  DATABASE_IDENTITY_SUPERSEDE_FEATURE_FLAGS_CONTRACT_SQL,
  DATABASE_IDENTITY_USERS_TABLE_SQL,
  DATABASE_IDENTITY_USER_CREDENTIALS_TABLE_SQL,
} from "../migration-manifest.js";

export const shorthands = undefined;

export function up(pgm: MigrationBuilder): void {
  pgm.sql(DATABASE_IDENTITY_USERS_TABLE_SQL);
  pgm.sql(DATABASE_IDENTITY_USER_CREDENTIALS_TABLE_SQL);
  pgm.sql(DATABASE_IDENTITY_CHALLENGES_TABLE_SQL);
  pgm.sql(DATABASE_IDENTITY_CHALLENGES_INDEXES_SQL);
  pgm.sql(DATABASE_IDENTITY_SESSIONS_TABLE_SQL);
  pgm.sql(DATABASE_IDENTITY_SESSIONS_INDEX_SQL);
  pgm.sql(DATABASE_IDENTITY_OUTBOX_TABLE_SQL);
  pgm.sql(DATABASE_IDENTITY_OUTBOX_INDEX_SQL);
  pgm.sql(DATABASE_IDENTITY_RATE_LIMITS_TABLE_SQL);
  pgm.sql(DATABASE_IDENTITY_RATE_LIMITS_INDEX_SQL);
  pgm.sql(DATABASE_IDENTITY_IDEMPOTENCY_TABLE_SQL);
  pgm.sql(DATABASE_IDENTITY_IDEMPOTENCY_INDEX_SQL);
  pgm.sql(DATABASE_IDENTITY_AUDIT_TABLE_SQL);
  pgm.sql(DATABASE_IDENTITY_AUDIT_INDEX_SQL);
  pgm.sql(DATABASE_IDENTITY_AUDIT_APPEND_ONLY_SQL);
  pgm.sql(DATABASE_IDENTITY_SUPERSEDE_FEATURE_FLAGS_CONTRACT_SQL);
  pgm.sql(DATABASE_IDENTITY_CONTRACT_INSERT_SQL);
}

export function down(pgm: MigrationBuilder): void {
  pgm.sql("DELETE FROM infra.migration_contracts WHERE migration_id = 3;");
  pgm.sql("DROP TABLE app.identity_audit_events RESTRICT;");
  pgm.sql("DROP FUNCTION app.reject_identity_audit_mutation();");
  pgm.sql("DROP TABLE app.identity_idempotency RESTRICT;");
  pgm.sql("DROP TABLE app.identity_rate_limits RESTRICT;");
  pgm.sql("DROP TABLE app.identity_email_outbox RESTRICT;");
  pgm.sql("DROP TABLE app.user_sessions RESTRICT;");
  pgm.sql("DROP TABLE app.email_verification_challenges RESTRICT;");
  pgm.sql("DROP TABLE app.user_credentials RESTRICT;");
  pgm.sql("DROP TABLE app.users RESTRICT;");
  pgm.sql(DATABASE_IDENTITY_RESTORE_FEATURE_FLAGS_CONTRACT_SQL);
}
