packages:
  - apps/*
  - packages/*

catalog:
  "@types/react": 19.2.17
  "@types/react-dom": 19.2.3
  react: 19.2.7
  react-dom: 19.2.7

overrides:
  postcss: 8.5.10

allowBuilds:
  sharp: true
  unrs-resolver: true
