packages:
  - apps/*
  - packages/*

autoInstallPeers: false
enableGlobalVirtualStore: false
engineStrict: true
saveExact: true
verifyDepsBeforeRun: error

catalog:
  "@types/react": 19.2.17
  "@types/react-dom": 19.2.3
  react: 19.2.7
  react-dom: 19.2.7

overrides:
  postcss: 8.5.10

allowBuilds:
  "@sentry/cli": false
  argon2: true
  sharp: true
  unrs-resolver: true
